### ISSUE TITLE
How does :Magic works ?

### ISSUE THREAD

**Issue by dbeniamine** [ardagnir/vizardry#6]
Hi,

I'm looking at `:Magic` commands family and I don't fully understand how it works, well actually I understand the vimscript code, but I don't get why vim should source the files `bundle/vizardry/magic/*.vim`. And when I try to add vim commands in a magic file, it does not seems to be sourced ...

Actually  I was thinking to move theses files, In something like  `bundle/vizardry-magic/plugin/magic-<name>.vim` to avoid adding file inside a directory that belongs to an external bundle, but I don't like to change things when I don't understand how they work.

Can you help me ?

Thanks,
David

**Comment by ardagnir** [comment]
Magic files are in bundle/vizardry/plugin/magic/ not bundle/vizardry/magic/

I put them in the Vizardry dir so they would be disabled if Vizardry is disabled or uninstalled. I didn't think people expected a plugin's features to outlast the plugin.

**Comment by dbeniamine** [comment]
Thanks, so I broke this part of my version of Vizardry, I'll fix it ASAP.

You are perfectly right for the problem of outlasting the bundle, so I guess I shouldn't change the default magic directory, but give the user the ability to set it and recommend to change it if using `submodule` mode, explaining that mean removing it by hand when removing Vizardry.

Thanks for your answers,
David
